### ISSUE TITLE
text sometimes inserted as blob into text field

### ISSUE THREAD

**Issue by jeffswitzer** [NathanaelA/nativescript-sqlite#86] opened 2018-04-24 23:52 UTC
This may or may not being an issue with nativescript-sqlite. I have an app that pulls JSON from a server and then inserts rows into an sqlite table from that JSON. Sometimes when inserting one of the text fields gets inserted as a BLOB. Then when the app later queries the row containing the blob from the table this error is thrown:

`Error: Uncaught (in promise): TypeError: null is not an object (evaluating 'NSString.stringWithUTF8String(sqlite3_column_text(statement, column)).toString')`

Any idea why text would be converted to a blob sometimes? If I run the same test multiple times sometimes the text gets inserted fine, sometimes with the same row the text is inserted as a blob. So far I've only experienced this on IOS.

Here is an example of the text that sometimes is converted: 

> 6.2 River Miles in length from St. Anthony Falls (RM 853.8 at Minneapolis) to Lock & Dam #1 (RM 847.6 at Minneapolis, MN)

The create statement for the table looks like this (the comment field is the one that gets intermittent blob rows):
`CREATE TABLE stations (station_id integer,observer_id integer,station_name text,latitude numeric,longitude numeric,lat_lon_datum text,elevation_m numeric,comment text,street_address text,city text,state text,country text,postal_code text,elevation_source text,lat_lon_source text,development text,slope_type text,slope_location text,slope_faces text,active numeric,elevation_user_m numeric,elevation_calc_m numeric,elevation_calc_source text,latitude_user numeric,longitude_user numeric,load_key text,land_cover text,forest_type text,bodies_of_water numeric,bodies_of_water_units numeric,area_of_site numeric,area_of_site_units_id numeric,distance_nearest_road numeric,distance_nearest_road_units_id numeric,create_date text,public integer,has_dogs integer,has_cats integer,has_other_domestic integer,other_domestic text,has_garden integer,has_feeder integer,has_nestbox integer,has_fruit integer,has_birdbath integer,has_other_features integer,gmt_difference numeric,short_latitude numeric,short_longitude numeric,file_url text,network_id integer,person_id integer,deleted undefined)`

**Comment by NathanaelA** [comment] 2018-04-25 01:15
Actually based on the error I don't believe it got converted to a blob -- it looks like it wrote a "null" to the table; and the code assumes that a valid string will be read, so it throws the error when it gets a null out.   1. Do you see this issue on the emulator or only real devices?
2. Can you show me the insert statement?
3. If on emulator, can you get the sqlite table off of it so that we can view it and verify what the data looks like (any number of sqlite tools can open the table if you pull if from the device).

**Comment by jeffswitzer** [comment] 2018-04-25 16:40
Appreciate the quick response. The reason I believe it's a blob is because in my sqlite editor I see this:

<img width="838" alt="screen shot 2018-04-25 at 9 29 01 am" src="https://user-images.githubusercontent.com/8194284/39259482-5b52fbfe-486b-11e8-87bc-605d77c7d9aa.png">

1. So far this has only been on a real device, I'll attempt to reproduce on an emulator.

2. This is one of the offending insert statements (bolded the part that later shows as a blob). I log the insert queries into a logging table directly before the query is ran:

> INSERT INTO stations (station_id,observer_id,station_name,latitude,longitude,lat_lon_datum,elevation_m,**comment**,street_address,city,state,country,postal_code,elevation_source,lat_lon_source,development,slope_type,slope_location,slope_faces,active,elevation_user_m,elevation_calc_m,elevation_calc_source,latitude_user,longitude_user,load_key,land_cover,forest_type,bodies_of_water,bodies_of_water_units,area_of_site,area_of_site_units_id,distance_nearest_road,distance_nearest_road_units_id,create_date,public,has_dogs,has_cats,has_other_domestic,other_domestic,has_garden,has_feeder,has_nestbox,has_fruit,has_birdbath,has_other_features,gmt_difference,short_latitude,short_longitude,file_url,network_id,person_id,deleted) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) VALUES: 23761,2927,UMR-Pool 1,44.948887,-93.202942,WGS84,216,**6.2 River Miles in length from St. Anthony Falls (RM 853.8 at Minneapolis) to Lock & Dam #1 (RM 847.6 at Minneapolis, MN)**, East Lake Street,Minneapolis,MN,,55406,Google Elevation Service,Google Maps,Urban,,,,1,,222,Google Elevation Service,,,,Other (please describe in comments box),,,,,,,,2016-06-09 00:00:00,0,,,,,-1,,,,,,-6,44.949,-93.203,,434,2927,false

3. I've pulled the database from a real device and would be happy to share privately. If you want to take a look tap me at jeff{dot}switzer{at}gmail.com and I'll reply with it attached.

**Comment by jeffswitzer** [comment] 2018-04-25 19:34
A few more findings:

- I can also get it to happen on the ios simulator.
- I can't get it to happen on an android device.
- When I check the sqlite table from two failed tests and compared the 86 inserted rows, the same two rows had blob in the comments column. So I thought it might be data specific, however I also noticed an additional blob in the second failed test in a completely different row under the station_name column. The text that should have been inserted in this case is "Joseph Wood Krutch Garden U Arizona mall"

This [stack exchange](https://stackoverflow.com/questions/28142226/sqlite-for-swift-is-unstable) may be related.

Finally, the code I use to insert looks like this (since the inserts are in a loop maybe I have something messed up with the awaits?):
```
...
for (var serverObject of serverObjects) {
    if (dbObjects.some((dbObject) => serverObject[this.primaryKey] == dbObject[this.primaryKey])) {
        let result = await this.updateInDatabase(serverObject);
     }
     else {
        let result = await this.insertIntoDatabase(serverObject);
     }
 }
...

async insertIntoDatabase(objectToInsert) {
        let mappedObjectsToInsert = this.tableColumns.map((column) => {
            if (column === 'deleted')
                return false;
            else
                return objectToInsert[column]
        });
        let questionMarks = this.tableColumns.map((el) => '?').join(',');
        let query = `INSERT INTO ${this.tableName} (${this.tableColumns.join(',')}) VALUES (${questionMarks})`;
        return this._databaseService.runQueryWithValues(this.getDatabase(), query, mappedObjectsToInsert)
    };

runQueryWithValues(database, query, values, logQuery = true) {
        return database.execSQL(query, values)
            .then(result => {
                if(logQuery)
                    this.logDbInfo(`QUERY: ${query} VALUES: ${values}`);
                return result;
            })
            .catch(err => {
                console.log('ERROR: ' + err);
                if(logQuery)
                    this.logDbError(`QUERY: ${query} VALUES: ${values} ERROR: ${err}`);
            });
    }
```

**Comment by NathanaelA** [comment] 2018-04-25 20:54
Hmm, that is interesting.  
1. So when you pulled the actual sqllite table; and opened it up locally; did those fields marked as blob actually have the text it was supposed to or was it random garbage?
2. Reading through that swift issue; I can see that there is a potential that there is a GC issue; the NativeScript GC is kicking in and killing the value on iOS before it is being used.   I'll have to look into the SQLITE_TRANSIENT and see if I can use it to force the value to be copied and used before the NS side GC's it...  That would explain why it is randomly happening to you...

**Comment by NathanaelA** [comment] 2018-04-25 21:45
Interesting -- Awesome -- I bet he corruption is a GC event.   That would explain the random reports over the years of some corruption that I have been unable to find.   I took a look at my SQLite code; and I'm not sending the Transient flag; which means that this is a very real possibility to the cause.   

 I'll add this flag and then if you don't mind can you test and see if you can duplicate the issue anymore?

I'm not 100% sure how to pass this flag from NS properly; as it is a weird pointer type; but if you don't mind testing a couple versions; I think we can potentially nail it down...

**Comment by jeffswitzer** [comment] 2018-04-25 22:01
Don't mind testing at all. Your fix is my fix ;)

**Comment by NathanaelA** [comment] 2018-04-27 01:06
I have uploaded v2.20 which I believe will fix this issue.   Thanks for letting me know.   Please let me know if you see any more issues...

**Closed by NathanaelA** 2018-04-27 01:06 UTC
