### ISSUE TITLE
Help/Improve iOS retrieve data as object(SQLITE.RESULTSASOBJECT)

### ISSUE THREAD

**Issue by pierrediderot** [NathanaelA/nativescript-sqlite#3] opened 2015-10-28 21:04 UTC
Bro, sorry my english, because this time I use Google Translate.
--
I'm trying to recover data from SQLite, the Object Format (db.resultType (sqlite.RESULTSASOBJECT)). In android works perfectly, but already in the iOS does not work well.
Problems encountered:
1 - file: /// app (nativescript-sqlite-example) /main-page.js:38:24: CONSOLE LOG TypeError: colName.contains is not a function. (In 'colName.contains (cn)', 'colName.contains' is undefined)
1.1 - Fixed: I added the end of the script (sqlite.ios.js), the following code:
// HERE JS
if ( !Array.prototype.contains ) {
  Object.defineProperty(Array.prototype, 'contains', {
    enumerable: false,
    configurable: true,
    writable: true,
    value: function(searchElement/*, fromIndex*/) {
      if (this === undefined || this === null) {
        throw new TypeError('Cannot convert this value to object');
      }
      var O = Object(this);
      var len = parseInt(O.length) || 0;
      if (len === 0) { return false; }
      var n = parseInt(arguments[1]) || 0;
      if (n >= len) { return false; }
      var k;
      if (n >= 0) {
        k = n;
      } else {
        k = len + n;
        if (k < 0) k = 0;
      }
      while (k < len) {
        var currentElement = O[k];
        if (searchElement === currentElement ||
            searchElement !== searchElement && currentElement !== currentElement
        ) {
          return true;
        }
        k++;
      }
      return false;
    }
  });
}
-
2 - Method (_getResults) var cn = sqlite3_column_name (statement, i) .value; This not returning the column name, but the "index".
file: ///app/tns_modules/nativescript-sqlite/sqlite.js: 575: 28: CONSOLE LOG CN: 110
-- I tried to solve using other commands as sqlite3_column_origin_name, but not succeeded yet.

3 - Method (_getResult):
3.1 - I am having problem trying to retrieve a column of type text.
Note: 110 its a column "name", returned from sqlite3_column_name (statement, i) .value; the rest is "value"(text).
110: NSString {boundingRectWithSizeOptionsAttributesContext: function, cString: function, cStringLength: function, cStringUsingEncoding: function, canBeConvertedToEncoding: function, …}

3.2 - The int and float types are being returned as String, I just realized the parseInt or parseFloat, and went on to correctly return type.
--
I am using OSX 10.10.5, Xcode 6.4 SDK (8.4), 1.4.2 and NativeScript NativeScript-sqlite 1.0.0.

Note: I tried to https://github.com/NathanaelA/nativescript-sqlite-example, which uses NativeScript-sqlite 1.0.1 and had the same problem with iOS.

Am new development with NativeScript and javascript, I am striving to tackle this problem and help the community, please give me tips to help you and solve such problems.

For I am developing an application for company in which work and need to solve such "bugs"

In Android works fine !

**Comment by NathanaelA** [comment] 2015-10-29 00:37
1 & 2. I fixed the first two issues you mentioned and pushed a new version.

3. The third issue; I am not seeing.  It works for me.   Can you try the latest nativescript-sqlite-example and see if it still fails for you.  (I just pushed a new version of both the sqlite and example files).  This originally was failing in the app because of the column name failure.  But by fixing 1 & 2; this is now working properly on iOS also.

4. The int/float types are meant to be returned as strings.  This keeps them compatible with what occurs on the Android side.   Everything comes back as a string by design.  If you need it parsed back; then just use parseInt(value,10) on the result data to use it as a integer...

**Comment by pierrediderot** [comment] 2015-10-29 12:57
1 & 2 are OK !
\3.
3.1 - I am having problem trying to retrieve a column of type text.
// without NSString.stringWithUTF8String() in _getResult > sqlite3_column_text
Object
Numero: 1
Status: Reference {}

Object
Numero: 2
Status: Reference {}

// without NSString.stringWithUTF8String() in _getResult > sqlite3_column_text
Status: NSString {boundingRectWithSizeOptionsAttributesContext: function, cString: function, cStringLength: function, cStringUsingEncoding: function, canBeConvertedToEncoding: function, …}

NOTE: Will I have to upgrade my lib Sqlite3 ?
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include/sqlite3.h
// ======== //
3.2(\4) - Sorry about parsers(Int, Float), indeed
 you don't need .toString() in sqlite3_column_int() and sqlite3_column_double().
Example:
// == iOS == //
// without .toString()
Object
// NOTE Column name are returned after you put   // --> Numero(number): 1 <-- NOTE: This prop as Integer
Status: NSString {boundingRectWithSizeOptionsAttributesContext: function, cString: function, cStringLength: function, cStringUsingEncoding: function, canBeConvertedToEncoding: function, …}

Object
Numero(number): 2 <-- NOTE: This prop as Integer
Status: NSString {boundingRectWithSizeOptionsAttributesContext: function, cString: function, cStringLength: function, cStringUsingEncoding: function, canBeConvertedToEncoding: function, …}
--
// with .toString()
Object
Numero(number): "1" <-- NOTE: This prop as String
Status: NSString {boundingRectWithSizeOptionsAttributesContext: function, cString: function, cStringLength: function, cStringUsingEncoding: function, canBeConvertedToEncoding: function, …}

Object
Numero(number): "2" <-- NOTE: This prop as String
Status: NSString {boundingRectWithSizeOptionsAttributesContext: function, cString: function, cStringLength: function, cStringUsingEncoding: function, canBeConvertedToEncoding: function, …}

// == Android == //
In Android both are correct, returned types and column name, since the first time test.
NOTE: Because you don't parse toString in respective methods. Like this cursor.get[Type]().toString().
Object
Numero(number): 1 <-- as integer
Status: "ocupada"

Object
Numero(number): 2 <-- as integer
Status: "livre"
// ------ //

I apologize, about anything and congratulations for your attention with me.

**Comment by NathanaelA** [comment] 2015-10-29 20:02
Thanks.  I'll take a look at that.

**Comment by NathanaelA** [comment] 2015-10-29 21:59
I have confirmed what you said that the Strings were being returned as NSStrings on iOS.  I have updated the code base to turn them into a JavaScript string.  So now the typeof will report 'string' rather than 'object'.  I have pushed v1.03 which fixes this issue.

**Comment by pierrediderot** [comment] 2015-10-30 12:23
Fellow, you don't see a difference between return:

Database.prototype._getResult = function(statement, column) {
    var resultType = sqlite3_column_type(statement, column);
    switch (resultType) {
        case 1: // Int
            var value = sqlite3_column_int(statement, column).toString();
            console.log("Integer value typeof", typeof value);
            return value;
        case 2: // Float
            var value = sqlite3_column_double(statement, column).toString();
            console.log("Float value typeof", typeof value);
            return value;
        case 3: // Text
            return NSString.stringWithUTF8String(sqlite3_column_text(statement, column)).toString();
        case 4: // Blob
            return null; // TODO: We don't currently support Blobs
        case 5: // Null
            return null;
        default:
            return NSString.stringWithUTF8String(sqlite3_column_text(statement, column)).toString();
    }
};

Console result ->
file:///app/tns_modules/nativescript-sqlite/sqlite.js:545:24: CONSOLE LOG Integer value typeof string
file:///app/tns_modules/nativescript-sqlite/sqlite.js:550:24: CONSOLE LOG Float value typeof string

// -- //
Database.prototype._getResult = function(statement, column) {
    var resultType = sqlite3_column_type(statement, column);
    switch (resultType) {
        case 1: // Int
            var value = sqlite3_column_int(statement, column);
            console.log("Integer value typeof", typeof value);
            return value;
        case 2: // Float
            var value = sqlite3_column_double(statement, column);
            console.log("Float value typeof", typeof value);
            return value;
        case 3: // Text
            return NSString.stringWithUTF8String(sqlite3_column_text(statement, column)).toString();
        case 4: // Blob
            return null; // TODO: We don't currently support Blobs
        case 5: // Null
            return null;
        default:
            return NSString.stringWithUTF8String(sqlite3_column_text(statement, column)).toString();
    }
};

Console result ->
file:///app/tns_modules/nativescript-sqlite/sqlite.js:545:24: CONSOLE LOG Integer value typeof number
file:///app/tns_modules/nativescript-sqlite/sqlite.js:549:24: CONSOLE LOG Float value typeof number

// -- //
Thanks for your attention.

**Comment by NathanaelA** [comment] 2015-10-30 21:03
Yeah, I noticed that earlier today and actually have another release I will be releasing soon...  Still running my tests to verify everything is working.

**Comment by NathanaelA** [comment] 2015-12-05 00:05
Erps, I forgot to mention that this is fixed in the latest release.   It now has the ability to do RESULTSASNATIVE or RESULTSASSTRING so that you can choose the result set types.

**Closed by NathanaelA** 2015-12-05 00:05 UTC
