### ISSUE TITLE
[HELP] - Can't find variable: sqlite3_open_v2 in iOS.

### ISSUE THREAD

**Issue by pierrediderot** [NathanaelA/nativescript-sqlite#2] opened 2015-10-26 19:24 UTC
Xcode Version 6.4 (SDK - 8.4)
## NativeScript Version 1.4.0

We failed to open database
ReferenceError: Can't find variable: sqlite3_open_v2
message: "Can't find variable: sqlite3_open_v2"
sourceURL: "file:///app/tns_modules/nativescript-sqlite/sqlite.js"
stack: "file:///app/tns_modules/nativescript-sqlite/sqlite.js:79:40↵initializePromise@[native code]↵Promise@[native code]↵Database@file:///app/tns_modules/nativescript-sqlite/sqlite.js:71:23↵GenericDAO@file:///app/database/generic.js:7:36↵MesaService@file:///app/services/mesa-service.js:18:20↵anonymous@file:///app/services/mesa-service.js:73:33↵__executeModule↵__loadModule↵require↵anonymous@file:///app/models/mesa.js:10:26↵__executeModule↵__loadModule↵require↵anonymous@file:///app/views/mesas/index.js:3:24↵__executeModule↵__loadModule↵require↵resolvePageFromEntry@file:///app/tns_modules/ui/frame/frame-common.js:45:36↵navigate@file:///app/tns_modules/ui/frame/frame-common.js:110:40↵navigate@file:///app/tns_modules/ui/frame/frame.js:28:43↵onLoaded@file:///app/tns_modules/ui/frame/frame.js:22:26↵viewDidLoad@file:///app/tns_modules/ui/frame/frame.js:202:29↵makeKeyAndVisible@[native code]↵didFinishLaunchingWithOptions@file:///app/tns_modules/application/application.js:132:39↵[native code]↵onReceive@file:///app/tns_modules/application/application.js:55:32↵UIApplicationMain@[native code]↵start@file:///app/tns_modules/application/application.js:191:26↵anonymous@file:///app/app.js:9:18↵__executeModule↵__loadModule"

**Comment by NathanaelA** [comment] 2015-10-26 20:05
This is an issue with the new NativeScript command line.  I do have a possible work around if you want to continue working today; or I should have a new version of the Sqlite that will be released in the next couple of days that is now a very simple install on Macintosh

The workaround is to copy the modulemap.module file into the /platforms/ios/internal
(You may have to create that folder).

**Comment by pierrediderot** [comment] 2015-10-26 20:22
Tks bro, worked for me. But I need understand this(I should have a new version of the Sqlite that will be released in the next couple of days that is now a very simple install on Macintosh).
In feel days/weeks, we have a new version from SQLite correct ? I have to update in my mac osx or update my Xcode to new version ?

I'm confuse with this info(update new version from SQLite)....
OBS: In android is too easy to work. After update in fell days/weeks, I'll have a any problem ?

Sorry about my english.

**Comment by NathanaelA** [comment] 2015-10-26 20:45
No, if you are already working -- you are good to go.  

All the new version of nativescript-sqlite does is make the install procedure automatic for iOS.  No other changes.

**Comment by siberian1967** [comment] 2015-12-11 08:39
I am seeing this here (new project, have not used sqlite and nativescript together before)

```
Dec 11 00:37:59 Johns-MacBook-Pro Demo[72237]: CONSOLE ERROR file:///app/main-view-model.js:5:22: We failed to open database ReferenceError: Can't find variable: sqlite3_open_v2
Dec 11 00:37:59 Johns-MacBook-Pro assertiond[16923]: assertion failed: 15B42 13B137: assertiond + 12188 [93FFE0B6-5C27-387F-B32A-6EE378BBB22A]: 0x1
Dec 11 00:37:59 Johns-MacBook-Pro Demo[72237]: CONSOLE ERROR file:///app/main-view-model.js:17:18: We failed to open database ReferenceError: Can't find variable: sqlite3_open_v2
```

Any other info I can give to hunt it down?

```
Johns-MacBook-Pro:Stratfor jarmstrong$ tns --version
1.5.1
```

Tx!

**Comment by stefalda** [comment] 2016-10-03 12:02
I've found the same problem working with iOS 10 SDK and XCode 8.
Hi,
I've tried to reinstall CocoaPods but the problem is still there.
I've been able to fix it (but sometimes it comes back) by opening XCode and manually linking the ibsqlite3.dylib library from /usr/libs... using some info from this thread on 
[http://stackoverflow.com/questions/31420166/libsqlite3-dylib-and-libz-dylib-missing-in-xcode-7-how-do-i-use-parse](http://stackoverflow.com/questions/31420166/libsqlite3-dylib-and-libz-dylib-missing-in-xcode-7-how-do-i-use-parse)

I don't know if you have a permanent fix for this.

**Comment by pap5508** [comment] 2017-03-02 10:48
@NathanaelA : Please help me out to solve error.

Error While Inserting Data in Sqlite for Offile line support of an Application.

Error : `CONSOLE LOG file:///app/app.component.js:16:24: OPEN DB ERROR ReferenceError: Can't find variable: sqlite3_open_v2
CONSOLE LOG file:///app/app.component.js:16:24: OPEN DB ERROR ReferenceError: Can't find variable: sqlite3_open_v2
***** Fatal JavaScript exception - application has been terminated. *****
Native stack trace:
2017-03-01 11:37:21.331984 TestOfflineApp[4727:348806] 1   0x6c12c5 NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
1   0x6c12c5 NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
2017-03-01 11:37:21.334814 TestOfflineApp[4727:348806] 2   0xb767b5 ffi_closure_inner_SYSV
2   0xb767b5 ffi_closure_inner_SYSV
2017-03-01 11:37:21.335042 TestOfflineApp[4727:348806] 3   0xb790b8 ffi_closure_SYSV
3   0xb790b8 ffi_closure_SYSV
2017-03-01 11:37:21.335722 TestOfflineApp[4727:348806] 4   0x23244fdf <redacted>
4   0x23244fdf <redacted>
2017-03-01 11:37:21.336525 TestOfflineApp[4727:348806] 5   0x230d1ee5 <redacted>
5   0x230d1ee5 <redacted>
2017-03-01 11:37:21.337501 TestOfflineApp[4727:348806] 6   0x230d1e73 <redacted>
6   0x230d1e73 <redacted>
2017-03-01 11:37:21.338277 TestOfflineApp[4727:348806] 7   0x230bbf97 <redacted>
7   0x230bbf97 <redacted>
2017-03-01 11:37:21.339047 TestOfflineApp[4727:348806] 8   0x230bc0b5 <redacted>
8   0x230bc0b5 <redacted>
2017-03-01 11:37:21.340020 TestOfflineApp[4727:348806] 9   0x230d179b <redacted>
9   0x230d179b <redacted>
2017-03-01 11:37:21.340805 TestOfflineApp[4727:348806] 10  0x230d12e7 <redacted>
10  0x230d12e7 <redacted>
2017-03-01 11:37:21.341572 TestOfflineApp[4727:348806] 11  0x230cbee7 <redacted>
11  0x230cbee7 <redacted>
2017-03-01 11:37:21.342339 TestOfflineApp[4727:348806] 12  0x2309ccf5 <redacted>
12  0x2309ccf5 <redacted>
2017-03-01 11:37:21.343149 TestOfflineApp[4727:348806] 13  0x2383898d <redacted>
13  0x2383898d <redacted>
2017-03-01 11:37:21.344624 TestOfflineApp[4727:348806] 14  0x238325d3 <redacted>
14  0x238325d3 <redacted>
2017-03-01 11:37:21.344882 TestOfflineApp[4727:348806] 15  0x1dfac71b <redacted>
15  0x1dfac71b <redacted>
2017-03-01 11:37:21.345052 TestOfflineApp[4727:348806] 16  0x1dfac225 <redacted>
16  0x1dfac225 <redacted>
2017-03-01 11:37:21.345438 TestOfflineApp[4727:348806] 17  0x1dfaa4fb <redacted>
17  0x1dfaa4fb <redacted>
2017-03-01 11:37:21.345594 TestOfflineApp[4727:348806] 18  0x1def9533 CFRunLoopRunSpecific
18  0x1def9533 CFRunLoopRunSpecific
2017-03-01 11:37:21.345741 TestOfflineApp[4727:348806] 19  0x1def9341 CFRunLoopRunInMode
19  0x1def9341 CFRunLoopRunInMode
2017-03-01 11:37:21.346011 TestOfflineApp[4727:348806] 20  0x1f6d0bfd GSEventRunModal
20  0x1f6d0bfd GSEventRunModal
2017-03-01 11:37:21.346866 TestOfflineApp[4727:348806] 21  0x23107e27 <redacted>
21  0x23107e27 <redacted>
2017-03-01 11:37:21.347940 TestOfflineApp[4727:348806] 22  0x23102551 UIApplicationMain
22  0x23102551 UIApplicationMain
2017-03-01 11:37:21.348397 TestOfflineApp[4727:348806] 23  0xb7902c ffi_call_SYSV
23  0xb7902c ffi_call_SYSV
2017-03-01 11:37:21.348618 TestOfflineApp[4727:348806] 24  0xb764f9 ffi_call
24  0xb764f9 ffi_call
2017-03-01 11:37:21.349054 TestOfflineApp[4727:348806] 25  0x68d397 NativeScript::FFICall::call(JSC::ExecState*)
25  0x68d397 NativeScript::FFICall::call(JSC::ExecState*)
2017-03-01 11:37:21.352421 TestOfflineApp[4727:348806] 26  0x95a40f JSC::LLInt::setUpCall(JSC::ExecState*, JSC::Instruction*, JSC::CodeSpecializationKind, JSC::JSValue, JSC::LLIntCallLinkInfo*)
26  0x95a40f JSC::LLInt::setUpCall(JSC::ExecState*, JSC::Instruction*, JSC::CodeSpecializationKind, JSC::JSValue, JSC::LLIntCallLinkInfo*)
2017-03-01 11:37:21.352993 TestOfflineApp[4727:348806] 27  0x959e8b llint_slow_path_call
27  0x959e8b llint_slow_path_call
2017-03-01 11:37:21.353407 TestOfflineApp[4727:348806] 28  0x9615ab llint_entry
28  0x9615ab llint_entry
2017-03-01 11:37:21.353790 TestOfflineApp[4727:348806] 29  0x9615b7 llint_entry
29  0x9615b7 llint_entry
2017-03-01 11:37:21.354783 TestOfflineApp[4727:348806] 30  0x9615b7 llint_entry
30  0x9615b7 llint_entry
2017-03-01 11:37:21.355173 TestOfflineApp[4727:348806] 31  0x9615b7 llint_entry
31  0x9615b7 llint_entry
JavaScript stack trace:
1   _rethrowWithContext@file:///app/tns_modules/@angular/core/bundles/core.umd.js:12760:77
2   @file:///app/tns_modules/@angular/core/bundles/core.umd.js:12777:46
3   @[native code]
4   @file:///app/tns_modules/nativescript-angular/renderer.js:213:31
5   invoke@file:///app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:190:33
6   onInvoke@file:///app/tns_modules/@angular/core/bundles/core.umd.js:4391:47
7   invoke@file:///app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:189:42
8   run@file:///app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:83:49
9   zonedCallback@file:///app/tns_modules/nativescript-angular/renderer.js:212:27
10  notify@file:///app/tns_modules/tns-core-modules/data/observable/observable.js:149:31
11  _emit@file:///app/tns_modules/tns-core-modules/data/observable/observable.js:168:24
12  _raiseTap@file:///app/tns_modules/tns-core-modules/ui/action-bar/action-bar-common.js:318:19
13  tap@file:///app/tns_modules/tns-core-modules/ui/action-bar/action-bar.js:248:28
14  UIApplicationMain@[native code]
15  start@file:///app/tns_modules/tns-core-modules/application/application.js:251:26
16  bootstrapApp@file:///app/tns_modules/nativescript-angular/platform-common.js:68:28
17  bootstrapModule@file:///app/tns_modules/nativescript-angular/platform-common.js:56:26
18  anonymous@file:///app/main.js:5:57
19  evaluate@[native code]
20  moduleEvaluation@[native code]
21  @[native code]
22  promiseReactionJob@[native code]
JavaScript error:
2017-03-01 11:37:21.358255 TestOfflineApp[4727:348806] file:///app/tns_modules/@angular/core/bundles/core.umd.js:12760:77: JS ERROR Error: Error in app.component.html:1:4 caused by: undefined is not an object (evaluating 'this.database.execSQL')
file:///app/tns_modules/@angular/core/bundles/core.umd.js:12760:77: JS ERROR Error: Error in app.component.html:1:4 caused by: undefined is not an object (evaluating 'this.database.execSQL')`


Please find attached Sample Program code.
[sample.zip](https://github.com/NativeScript/NativeScript/files/810404/sample.zip)

Environment: `node v6.9.2`, `Xcode 8.2.1`,` CLI 2.5.2`, `cocoa pods : 1.2.0`

**Comment by NathanaelA** [comment] 2017-03-02 11:34
@pap5508 - Have you tried:
1. `tns platform remove ios` then `tns platform add ios`
2. de-install app from phone/emulator (i.e. long press, then hit the "X" on the app) and then `tns run ios`

**Comment by pap5508** [comment] 2017-03-02 13:38
@NathanaelA : I have tried that too still same Error

**Comment by pap5508** [comment] 2017-03-06 13:34
@NathanaelA : Is there any other way to resolve this error..?? even though i have tried your suggestion bt not works...

**Comment by NathanaelA** [comment] 2017-03-06 17:34
Have you tried the demo project?   Does it work on your machine?

**Comment by NathanaelA** [comment] 2017-03-06 18:42
I just tried my demo on iOS and it does appear something in 2.5.x broke something.

**Comment by NathanaelA** [comment] 2017-03-06 19:15
I take that back my demo is working properly; I had messed up a path when I was updating my demo to 2.5 runtimes.     I can't say for sure why you aren't able to use it; but I would try to clone my git repo and verify the demo is working properly for you.  Then proceed from there.

Since I am a freelancer/consultant -- I do offer paid commercial support for any of my plugins, but other than making sure my plugins continues to work (for free) I don't offer any other free support beyond the real basics.

**Closed by NathanaelA** 2017-03-06 19:15 UTC

**Comment by sm1ddy** [comment] 2017-03-25 00:45
Hi

I've been experiencing this issue in Xcode 8.2.1, iOS 10 and thought I'd add a suggestion.

In my case, I found that it might relate to where the project folder resides on your computer.
My main project sits under a long directory path, whenever I create any project under this folder (even a basic demo) I receive the error.

Creating identical projects on my desktop, however, seems to work absolutely fine.

I don't know how to troubleshoot or investigate this but I thought I'd throw it in as a suggestion.

**Comment by NathanaelA** [comment] 2017-03-25 01:21
@sm1ddy - That is very interesting, I've never heard of a max path length issue on Mac's; but maybe their is one in one of the tns tools.  

 My current mac directory structure is:
~/Source/\<apps>
~/Source/Repos/\<any plugins>

So my path is pretty short in all reality and this works great for me, on windows my path is about the same size as I actually have /source/nativescript/\<apps> and /source/nativescript/repos/\<plugins>   I find that if I can keep it fairly close to the root on windows I don't run into the 255 path limit that can occur while it is building android apps.

**Comment by stevegardnersa** [comment] 2017-09-05 12:32
I had the same issue and tried moving it right to the root of my system and the issue persisted. I eventually found that the problem was that my project folder name had spaces in it. I'm wondering if this isn't the actual issue and not the path length. 

It seems to only be an issue with iOS. My Android app built and ran fine.
