### ISSUE TITLE
Module not found: Error: Can't resolve 'nativescript-sqlite-commercial'

### ISSUE THREAD

**Issue by lord-zeus** [NathanaelA/nativescript-sqlite#102] opened 2018-10-12 17:44 UTC
I'm building a mobile application with nativescript-vue. I installed this plugin and on running ` tns run android --bundle` it gives me Module not found: Error: Can't resolve 'nativescript-sqlite-commercial' && 
Module not found: Error: Can't resolve 'nativescript-sqlite-encrypted'

**Comment by NathanaelA** [comment] 2018-10-13 00:03
Yeah, that actually doesn't surprise me.      Webpacking can't find the commercial/encrypted modules (since you don't have them).   They are hard coded requires into the current version of sqlite, but I use a try/catch to detect if you don't actually have them.   I'll have to come up with a different way to do this for webpack...

**Comment by ludwiktrammer** [comment] 2018-10-24 14:12
I can confirm the problem. I'm having the same issue with NativeScript 4.2.

**Comment by ppritcha** [comment] 2018-11-12 22:55
I have this issue with NativeScript 5.0.

**Comment by sebawita** [comment] 2018-11-23 09:54
In Readme, there is an instruction to install the additional modules, however these two modules are not available on npm. 

***optional***
* `tns plugin add nativescript-sqlite-commercial`
* `tns plugin add nativescript-sqlite-encrypted`

Although, this doesn't break the app, the warnings are a bit concerning, and hard to ignore.

**Comment by ludwiktrammer** [comment] 2018-11-23 09:59
As a workaround, I made the warning disappear by instructing webpack to ignore those packages (i.e., not be concerned with making them part of the package) by adding this to webpack config.

    externals: {
         'nativescript-sqlite-commercial': 'nativescript-sqlite-commercial',
         'nativescript-sqlite-encrypted': 'nativescript-sqlite-encrypted',
    },

**Comment by sebawita** [comment] 2018-11-23 11:17
@ludwiktrammer that is a nice workaround. I just wish it was possible to embed webpack configs into the plugin directly, so that we wouldn't need to do it manually for each project.

**Comment by NathanaelA** [comment] 2019-04-07 05:41
I have updated the documentation a few versions back with Ludwick's information.   (Thanks!)    So closing this issue as the docs now spell out how to eliminate the issue.  :grinning:

**Closed by NathanaelA** 2019-04-07 05:41 UTC
Labels: bug

**Comment by rdbhagat999** [comment] 2019-08-10 06:46
I have cloned the following repo
`https://github.com/sanjay-patel/nativescript-todo-app`
I'm new to NativeScript. I'm using Angular v8, NativeScript cli v6.
```
"tns-android": {
      "version": "6.0.0"
    },
    "tns-ios": {
      "version": "6.0.1"
    },
"@nativescript/schematics": "^0.7.0",
"@schematics/angular": "^8.0.0",
"nativescript-angular": "~8.0.0",
"nativescript-sqlite": "^2.3.3",
```

If you can update your example to show how to include the following in webpack config?
```
externals: {
     'nativescript-sqlite-commercial': 'nativescript-sqlite-commercial',
     'nativescript-sqlite-encrypted': 'nativescript-sqlite-encrypted',
},
```
It would be even better if you can update the todo app link I have provided.

**Comment by dlcole** [comment] 2019-08-13 18:48
I have to echo the comment from @rdbhagat999 .  I'm upgrading to {N} 6.0 which requires WebPack.   In webpack.config.js I see the line 

    const externals = nsWebpack.getConvertedExternals(env.externals);

So I'm really confused as to where the externals object noted in the post from @ludwiktrammer  would go.

**Comment by ludwiktrammer** [comment] 2019-08-13 19:14
@dlcole You are correct. Since I made my previous comment, NativeScript added its own externals management to the default webpack configuration, making this more challenging - now you have to merge those two. 

In my projects, I add the following code immediately after the `const externals = ...` line:

```
    let extendedExternals = {
        "nativescript-sqlite-commercial": "nativescript-sqlite-commercial",
        "nativescript-sqlite-encrypted": "nativescript-sqlite-encrypted",
        "react-native-sqlite-storage": "react-native-sqlite-storage",
        ...externals,
    };
```

and then change this:

```
    const config = {
        mode: uglify ? "production" : "development",
        context: appFullPath,
        externals,
```

to this:

```
    const config = {
        mode: uglify ? "production" : "development",
        context: appFullPath,
        externals: extendedExternals,
```

(i.e., `externals,` becomes `externals: extendedExternals,`).

Note: Do not override the existing `externals` variable - this will make things bring silently in ways that are hard to debug (since the same variable is then used later in the file in conditional statements based on dubious assumptions, using `externals` as a proxy to distinguish full builds and preview builds).

**Comment by dlcole** [comment] 2019-08-13 19:32
@ludwiktrammer - I copied your code verbatim and that eliminated the sqlite build warnings.  Thanks!

**Comment by EdwardMwaura** [comment] 2019-08-20 12:47
@ludwiktrammer 's way fixed it. Thanks

**Comment by niDAH** [comment] 2019-08-20 14:01
Thanks @ludwiktrammer worked perfectly!

**Comment by toppa80** [comment] 2019-09-26 17:19
Hi,

I still get the error 

```
[19-09-26 19:08:03.485] (CLI) WARNING in ../node_modules/nativescript-sqlite/sqlite.js
[19-09-26 19:08:03.485] (CLI) Module not found: Error: Can't resolve 'nativescript-sqlite-commercial' in '/private/tmp/builds/_/162e9f6ab920fd1c01e8616cba4b8408ece3a68a/6.1.2/6.1.0/EAviationEFB/node_modules/nativescript-sqlite'
[19-09-26 19:08:03.485] (CLI)  @ ../node_modules/nativescript-sqlite/sqlite.js
[19-09-26 19:08:03.485] (CLI)  @ ./app-root.js
[19-09-26 19:08:03.485] (CLI)  @ . sync (?<!\\bApp_Resources\\b.*)\\.(xml|css|js|(?<!\\.d\\.)ts|(?<!\\b_[\\w-]*\\.)scss)$
[19-09-26 19:08:03.485] (CLI)  @ ./app.js
[19-09-26 19:08:03.485] (CLI) WARNING in ../node_modules/nativescript-sqlite/sqlite.js
[19-09-26 19:08:03.485] (CLI) Module not found: Error: Can't resolve 'nativescript-sqlite-encrypted' in '/private/tmp/builds/_/162e9f6ab920fd1c01e8616cba4b8408ece3a68a/6.1.2/6.1.0/EAviationEFB/node_modules/nativescript-sqlite'
[19-09-26 19:08:03.485] (CLI)  @ ../node_modules/nativescript-sqlite/sqlite.js
[19-09-26 19:08:03.485] (CLI)  @ ./app-root.js
[19-09-26 19:08:03.485] (CLI)  @ . sync (?<!\\bApp_Resources\\b.*)\\.(xml|css|js|(?<!\\.d\\.)ts|(?<!\\b_[\\w-]*\\.)scss)$
[19-09-26 19:08:03.485] (CLI)  @ ./app.js

```

I added **{ from: { glob: "\*\*/*.sqlite"} },** to the code like shown below:

```
new CopyWebpackPlugin([
                { from: { glob: "fonts/**" } },
                { from: { glob: "**/*.jpg" } },
                { from: { glob: "**/*.png" } },
                { from: { glob: "**/*.sqlite"} },                
], { ignore: [`${relative(appPath, appResourcesFullPath)}/**`] }),
new nsWebpack.GenerateNativeScriptEntryPointsPlugin("bundle"),
```


How do I now add 

```
externals: {
     'nativescript-sqlite-commercial': 'nativescript-sqlite-commercial',
     'nativescript-sqlite-encrypted': 'nativescript-sqlite-encrypted',
},
```

to the code?
