### ISSUE TITLE
Cannot find module 'nativescript-sqlite'

### ISSUE THREAD

**Issue by ikhsan017** [NathanaelA/nativescript-sqlite#60] opened 2017-09-26 05:17 UTC
Hi Nathan, thanks for building great plugins for nativescript.

However, when I try to build my project, I got this error
```
app/shared/services/database-migrator.service.ts(2,24): error TS2307: Cannot find module 'nativescript-sqlite'.
```
I try to clean plaform, remove node_modules and reinstall tns, but those error keep appearing

here is my package.json
```
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "com.xsanisty.logsheettns",
    "tns-android": {
      "version": "3.2.0"
    }
  },
  "android": {
    "markingMode": "none"
  },
  "scripts": {
    "lint": "tslint \"app/**/*.ts\"",
    "ns-bundle": "ns-bundle",
    "publish-ios-bundle": "npm run ns-bundle --ios --publish-app",
    "generate-android-snapshot": "generate-android-snapshot --targetArchs arm,arm64,ia32 --install",
    "start-android-bundle": "npm run ns-bundle --android --run-app",
    "start-ios-bundle": "npm run ns-bundle --ios --run-app",
    "build-android-bundle": "npm run ns-bundle --android --build-app",
    "build-ios-bundle": "npm run ns-bundle --ios --build-app"
  },
  "dependencies": {
    "@angular/animations": "~4.1.0",
    "@angular/common": "~4.1.0",
    "@angular/compiler": "~4.1.0",
    "@angular/core": "~4.1.0",
    "@angular/forms": "~4.1.0",
    "@angular/http": "~4.1.0",
    "@angular/platform-browser": "~4.1.0",
    "@angular/router": "~4.1.0",
    "angular2-jwt": "^0.2.3",
    "moment": "^2.18.1",
    "nativescript-angular": "~3.1.0",
    "nativescript-barcodescanner": "^2.6.1",
    "nativescript-cardview": "^2.0.2",
    "nativescript-carousel": "^3.1.1",
    "nativescript-dev-sass": "^1.3.2",
    "nativescript-feedback": "^1.0.6",
    "nativescript-local-notifications": "^1.2.2",
    "nativescript-nfc": "^2.0.0",
    "nativescript-ngx-fonticon": "^2.2.3",
    "nativescript-pro-ui": "^3.1.3",
    "nativescript-sqlite": "^1.1.9",
    "nativescript-textinputlayout": "^2.0.0",
    "nativescript-theme-core": "~1.0.2",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.4.0",
    "tns-core-modules": "^3.2.0",
    "zone.js": "^0.8.17"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~4.1.0",
    "@ngtools/webpack": "~1.5.0",
    "babel-traverse": "6.25.0",
    "babel-types": "6.25.0",
    "babylon": "6.17.4",
    "codelyzer": "^3.2.0",
    "copy-webpack-plugin": "~4.0.1",
    "extract-text-webpack-plugin": "~3.0.0",
    "lazy": "1.0.11",
    "nativescript-css-loader": "~0.26.0",
    "nativescript-dev-typescript": "~0.5.0",
    "nativescript-dev-webpack": "^0.8.0",
    "nativescript-worker-loader": "~0.8.1",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.1.0",
    "tns-platform-declarations": "^3.2.0",
    "tslint": "^5.7.0",
    "typescript": "~2.5",
    "webpack": "~3.2.0",
    "webpack-bundle-analyzer": "^2.8.2",
    "webpack-sources": "~1.0.1"
  }
}
```

any suggestion?

Best regards,
Ikhsan

**Comment by NathanaelA** [comment] 2017-10-05 07:29
This is a duplicate of #50

**Closed by NathanaelA** 2017-10-05 07:29 UTC
Labels: duplicate
